### ISSUE TITLE
Moderator tool to create shared nodes

### ISSUE THREAD

**Issue by S-S-X** [S-S-X/metatool#16]
> <SX> now I got idea for new metatool that could replace shared user account used to place shared things
> <SX> tool could simply set owner of nodes to shared, no need to login with another account just to place some things to world

Create new tool that can replace logging in to shared account.
Things to implement:
- [x] Travelnets
- [x] Books
- [x] POI
- [x] Missions
- [x] Map markers

Configuration:
- [x] Configurable shared account name
- [x] Configurable privilege requirement, keep `ban` as default

**Comment by BuckarooBanzay** [comment]
How would you decide who can use that so it can't be abused?
A simple protection-check or priv-based?

**Comment by S-S-X** [comment]
> How would you decide who can use that so it can't be abused?
> A simple protection-check or priv-based?

There is PR open to add priv checks for protected stuff. By default everything is disallowed in protected areas.
But adding priv requirement maybe tool wide was plan.

**Comment by S-S-X** [comment]
Created tool that:
* Is not craftable and not in crafting guide.
* Is given via command to players who has required privilege `ban`.
* Can be used if
  * Player has `ban` privilege.
* Allow claiming ownership of book if
  * user is in protection.
  * or if book is marked as shared.
* Allow restoring ownership to shared account if
  * user is owner of book.
  * or book is marked as shared.
  * or area is not protected from user.

Tool adds metadata mark `sharetool_shared_node` with value `1`, without this marking other players, even with ban priv, should not be able to claim ownership in protected area but owner can still mark their own nodes as shared (as long as he can use tool).

Similar should work well with travelnets.

**Comment by SwissalpS** [comment]
things to add: POI and mission stones, maybe also map-markers

**Comment by S-S-X** [comment]
> things to add: POI and mission stones, maybe also map-markers

Thanks for suggestions, added these to list.

**Comment by S-S-X** [comment]
Help wanted for testing if anyone happens to have time or interested seeing how many bugs I managed to slip through...
Annoying protection messages caused by #24 (protector mod)

**Comment by S-S-X** [comment]
Travelnets done, maybe... changed other things a bit too, probably partially fixed protection messages. Might be that notification about protection wont appear for every case now but also should not give unnecessary notifications about protection.

Changed some other stuff while doing that, also few things in API like adding metatool.ns used to create/retrieve well defined namespaces for tools.

**Comment by S-S-X** [comment]
Merged latest stuff to master and to pandorabox server mods so new stuff will be tested there. I've also done some very basic testing on dev server, found few bugs with travelnets where:

If you have other travelnets in your travelnet network and transfer one of those to shared account after travelnet is transfered to shared account it might also stay in your network and will be accessible from your network to shared network travelnet.

Basically it allows to travel across networks from travelnet network owned by player who placed and transfered travelnet box to shared account network. This is one way trip and I did not find a way to travel back to player network from shared network.

Not so fatal but might be a bit confusing, can probably be fixed by placing another travelnet with same name to same network and then removing it but didnt test that.

edit. Fixed above ^^ #26 / #27

**Comment by S-S-X** [comment]
#37 extends configuration and allows configuring privileges for both tools and nodes, also uses default if there's no entry in config file.

edit. Merged to master, adds/changes a lot of stuff in API, adds unit testing, configuration merging seems consistent and has simple unit tests.
Sample configuration file metatool.cfg can be generated by setting minetest config `metatool_export_default_config = true`

**Comment by S-S-X** [comment]
Added support for mapserver:poi*, mapserver:label and missions:mission. branch sharetool.
