### ISSUE TITLE
Add books for luatool

### ISSUE THREAD

**Issue by S-S-X** [S-S-X/metatool#51]
So that code can be copied to/from books.
Not sure how lua tube / lua controller should be handled here.

Maybe those groups should be just merged so that lua controller code could be written into lua tube and vice versa.
That would make adding books easier for lua tube and lua controller code.

Also it is possible to write invalid code for lua controller so I don't see any reason why code stored in tool must be marked as lua controller or lua tube code. Tool node definitions should work just fine also when storage group for both is same.

**Comment by SwissalpS** [comment]
the lua controller can store more data than a book can. I remember using books for backups and having to split it up into multiple books.

**Comment by S-S-X** [comment]
Instead of this better option is to implement [#54 New text copy tool to work with books, posters, signs etc.](https://github.com/S-S-X/metatool/issues/54)
