### ISSUE TITLE
New text copy tool to work with books, posters, signs etc.

### ISSUE THREAD

**Issue by S-S-X** [S-S-X/metatool#54]
Allow reading text content from any node that displays text or contains text.
Allow writing to nodes that can be written without special tools.

- [x] basic_signs (r/w)
- [x] books (r/w)
- [x] display_modpack https://github.com/pyrollo/display_modpack (r/w)
- [x] default signs (r/w)
- [x] digiterms https://github.com/pyrollo/digiterms (r)
- [x] digilines:lcd (r)
- [x] digistuff panel & touchscreen (r)
- [x] geocache (r)
- [x] lua controller
- [x] lua tube (r/w)
- [x] posters (r/w)
- [x] travelnet (r)
       broken: only copies target name, was supposed to copy all travelnet names in network.

Extras:
- [x] Write title and author to lua controller / lua tube code as comments.
- [x] Parse title from lua controller / lua tube comments. Use coords only if suitable comment line not found. Use results as tool infotext.

API:
- [x] Allow leaving copy or paste function undefined.
- [x] Ability to set max size for tool storage.
- [x] Ability to set custom wield texture (different from inventory icon) and scaling.

This should also implement #51 Should it be just read or read+write? Luatool has other special functions for memory debugging and cloning.
If it would be just read then Luatool should still implement reading from books even if not writing to books...

Use feather for recipe if feather is available :chicken: 

Note https://github.com/S-S-X/metatool/issues/51#issuecomment-714035115 should probably also go through limits and apply those to not allow storing more data than normally possible, probably should not add splitting or at least no automatic splitting as it can get confusing to use.
Message about partial write could be good if target node should not store as much as tool storage contains:
> the lua controller can store more data than a book can. I remember using books for backups and having to split it up into multiple books.

**Comment by S-S-X** [comment]
Pen should be craftable and few nodes might somewhat work: books, lua controller, lua tube.
Most nodedefs are still empty and just set content and description to "NOT IMPLEMENTED".

**Comment by S-S-X** [comment]
> the lua controller can store more data than a book can. I remember using books for backups and having to split it up into multiple books.

Tested this a bit and I could not find any actual limits from code and was able to past over 300k bytes to book without using tool. Seems to be case for poster and at road_signs too, no actual limits.

**Comment by SwissalpS** [comment]
Seems to be working so far. I like that sneak and special work.
Have tested on nodes from: pick mesecons, basic_signs, textline
Have no idea about the microcontroller, at least I was not able to make it crash.
Am puzzled that you asked to test textline, that's a digiline display and did not work (was expected)

About Luacontroller: it would be nice to have the description of pen reflect which code it is carrying. The location is not helping much. Same ideas as what we discussed for luatool. I think a '-- Title: My Rad Lua Code' parsing the first x chars after '-- Title:' or just first occurence of 'Title:' would be helpful. Maybe even second line with 'Version:' if present.

Edit: I did not do any tests with special chars, only basic English characters.

**Comment by S-S-X** [comment]
@SwissalpS 
> Am puzzled that you asked to test textline

That one was because you can still copy text content from many nodes that wont allow writing text to.
From issue description:

> Allow reading text content from any node that displays text or contains text.
> Allow writing to nodes that can be written without special tools.

So you should be able to clone text from textline to book or poster for example but not from book to textline.

**Comment by S-S-X** [comment]
> The location is not helping much. Same ideas as what we discussed for luatool. I think a '-- Title: My Rad Lua Code' parsing the first x chars after '-- Title:' or just first occurence of 'Title:' would be helpful. Maybe even second line with 'Version:' if present.

That would probably be good option, coordinates are not that helpful but maybe still good to keep coordinates if suitable comment line not found. In other words first try to parse first comments and if that did not succeed then fall back to coordinates.

**Comment by S-S-X** [comment]
@SwissalpS added luac comment parsing, it should do this when copying code:
* Look through first lines starting with `--` and containing other text, skip empty lines and continue to next line.
* Check if line contains (case insensitive) `Title`, `Descr` or `Author` and has punctuation followed by text.
  * Contains `Title`: use text after punctuation truncated to 80 chars as title parameter and tool infotext.
  * Contains `Descr` followed by any alphabets (`-- DescRAPtion=` matches too...): use text after punctuation truncated to 80 chars as title parameter and tool infotext.
  * Contains `Author`: use text after punctuation truncated to 80 chars as source/author parameter.
* If no title/descr match found then add coordinates to infotext and leave storage parameter empty.

So this matches both:
```
-- Title: Yoyo LuaC
-- Author: It was I who did this
```
And this matches only title and leaves author out because there's code in between breaking lookup:
```
-- Description: Yoyo LuaC
local showstopper = "omg why"
-- Author: It was I who did this
```

When pasting code:
* If tool has stored author, add comment `-- Author: %s` before actual code but only if code does not also contain `-- Author: whoever`.
* If tool has stored title, add comment `-- Description: %s` before actual code but only if code does not already contain `-- Title: whatever` or `-- Desc: whatever` matched as described above.

Does that sound good enough?

**Comment by SwissalpS** [comment]
> And this matches only title and leaves author out because there's code in between breaking lookup:

probably meant to type 'description' instead of 'title'

**Comment by S-S-X** [comment]
> > And this matches only title and leaves author out because there's code in between breaking lookup:
> 
> probably meant to type 'description' instead of 'title'

Yes, kind of :smile: description would have been more clear, probably did not think much while writing that as title and description are technically fully interchangeable here.

Then another thing I did think about for a moment when planning behavior but forgot completely:
Block comments, those are not allowed here as comment parser is really stupid line matcher that just sees single source code line and 1. checks if that line seems to be comment 2. finds out if contents matches defined rules.

How important it would be to also allow block comments like this:
```lua
--[[
Title: Block comment code
Author: Official Commentator
--]]
```
Above wont work currently but following of course works because parser only cares about line it sees:
```lua
--[[
-- Title: Block comment code
-- Author: Official Commentator
--]]
```

**Comment by SwissalpS** [comment]
no need to support block comments, your second example demonstrates that. Besides, it's ok to have single line comments
on top for parser and then a block with the actual user facing info.
