### ISSUE TITLE
Add some kind of container settings cloning tool

### ISSUE THREAD

**Issue by S-S-X** [S-S-X/metatool#55]
Technic chests will get face lift soon, tool to copy settings was requested: https://github.com/mt-mods/technic/issues/73

> One other thing I like about fancy vendors is the wand. I would already like to have a wand for normal chests and technic machines to set the 'split incomming' and 'autosort' toggles. With more complex toggles, this wish will become even stronger.
https://github.com/mt-mods/technic/issues/73#issuecomment-716168139

Add tool that is aware of all common setting types and able to clone those between different kinds of chests and machines.
Add special setting lists so that type specific settings can be copy pasted too while still allowing pasting limited set of stored settings.

That way cloning from any to any chest or machine should work without problems and also allows adding type specific special behavior if needed.

This should be fairly straightforward to implement but needs some manual work to go through different mods adding chests, machines and other containers with settings.

- [x] Generic reusable way to detect Pipeworks formspec extensions during mod loading
- [x] Pipeworks extension for [default chests](https://gitlab.com/VanessaE/pipeworks/-/blob/master/compat-chests.lua#L239-242)
- [x] Pipeworks extension for [default furnace](https://gitlab.com/VanessaE/pipeworks/-/blob/master/compat-furnaces.lua#L276)
- [x] [technic chests](https://github.com/mt-mods/technic/tree/master/technic_chests)
   - Configuration is not yet protected! Currently there's no API methods for this, either have to reimplement protection or add proper API for chests.
- [x] [more_chests:shared](https://github.com/minetest-mods/more_chests/blob/cac8cddc6629e511ec04210a84fb9369d987da5b/shared.lua#L120-L128)
- [x] [digilines:chest](https://github.com/minetest-mods/digilines/blob/021c521c65e6184bceb7bb94e63c3b45a52671ea/inventory.lua#L55)
- [x] [Technic SCI](https://github.com/mt-mods/technic/blob/c89d0a1305ff6d0d07e153f92b008d86149f24a0/technic/machines/other/injector.lua#L85)
      :exclamation: Partially implemented, only generic switches (stack splitting)
- [x] Technic machines [base machine](https://github.com/mt-mods/technic/blob/master/technic/machines/register/machine_base.lua#L211)
      [Allow auto placing same upgrades?](https://github.com/mt-mods/technic/blob/c89d0a1305ff6d0d07e153f92b008d86149f24a0/technic/machines/register/machine_base.lua#L201-L202)
      :exclamation: Partially implemented, only generic switches (stack splitting)

**Comment by S-S-X** [comment]
Configuration cloning for technic chests should work but will clone unused meta data from higher tier chest to lower tier, for example copying settings from mithril chest will clone digiline configuration and if then applied to iron chest it will also set digiline meta data values.

Not sure how technic_chests handles this, is there unused meta data values for lower tier chests / stored color value for other than gold chest.
If there is then it should be fine to clone those here too but if chests itself wont do that then should probably somehow check it here too.

One way to check, if chests do always store something other than empty string _(empty string removes key from meta data)_ then it should be possible to check if there is already some value before overwriting it.
However if chests will `meta:set_string("something", "")` then it is not possible to check for existing keys and checks must be done with node name as there's no usable API for chests, this case is not forward compatible and cannot work with possible future chests and/or chests registered by other mod.

**Comment by OgelGames** [comment]
The only meta data set for every chest is `owner` (for locked chests) and `infotext`: https://github.com/mt-mods/technic/blob/master/technic_chests/register.lua#L80-L83

Everything else is set by the formspec: https://github.com/mt-mods/technic/blob/master/technic_chests/formspec.lua#L209-L253

These are all the values that are set:
* `owner` (string)
* `infotext` (string)
* `sort_mode` (int)
* `autosort` (int)
* `color` (int)
* `send_put` (int)
* `send_take` (int)
* `send_inject` (int)
* `send_pull` (int)
* `send_overflow` (int)
* `channel` (string)

Also locked chests support skeleton keys, which sets another value: https://github.com/mt-mods/technic/blob/master/technic_chests/register.lua#L221

Probably also worth mentioning that they all have the `technic_chest` group: https://github.com/mt-mods/technic/blob/master/technic_chests/register.lua#L18

**Comment by S-S-X** [comment]
> The only meta data set for every chest is `owner` (for locked chests) and `infotext`: https://github.com/mt-mods/technic/blob/master/technic_chests/register.lua#L80-L83

That is good and is assumed to be "special" field that cannot be applied to chests but is used for some security checks like skeleton key code cloning check.

> Everything else is set by the formspec: https://github.com/mt-mods/technic/blob/master/technic_chests/formspec.lua#L209-L253
> 
> These are all the values that are set:
> 
> * `owner` (string)
> * `infotext` (string)
> * `sort_mode` (int)
> * `autosort` (int)
> * `color` (int)
> * `send_put` (int)
> * `send_take` (int)
> * `send_inject` (int)
> * `send_pull` (int)
> * `send_overflow` (int)
> * `channel` (string)

Chests seems to also do some things directly with `splitstacks` meta data value, tool also reads/writes this one directly.

Seems that everything is added, for digiline channel and skeleton key cloning I was going to add configuration options to enable/disable those. Also planned to add per player configuration which could possibly later allow player to set preferences to copy/not to copy those two. Possibly also for color.
Currently after applying tool data to any chest it will also write all these values (if found from tool memory) to meta data even if values are not used in target chest.
Sounds like this is not very clean approach but as you say those are set through formspec so probably there's no currently any good way to detect which options target chest can actually use.

edit. some code here probably makes it bit more clear. those set_* functions will set value only if not nil:
https://github.com/S-S-X/metatool/blob/e951d841a7fe0f6b3468a22d74e9b1da69719939/containertool/nodes/technic_chests.lua#L98-L116

> Also locked chests support skeleton keys, which sets another value: https://github.com/mt-mods/technic/blob/master/technic_chests/register.lua#L221

Currently this can be copied if tool user is same as owner set for chest.

> Probably also worth mentioning that they all have the `technic_chest` group: https://github.com/mt-mods/technic/blob/master/technic_chests/register.lua#L18

That's exactly what I've used to collect chests :smile: 

For protection check I think it might be enough to call `technic.chests.change_allowed(pos, player, nil, true)` and allow copying configuration if that check passes? That is, handle configuration protection like if every chest would be locked.
