### ISSUE TITLE
Allow stacking empty tubetool wands?

### ISSUE THREAD

**Issue by S-S-X** [S-S-X/metatool#6]
Maybe allow stacking wands that do not have any configuration stored.
Basically that would need one wand item that carries metadata and other that never carries any metadata but allows stacking.

Copy function should be available for empty wands that do not store metadata and when those used with special+click or sneak+click it should take away one empty wand from stack and give one configured wand to inventory.

Useful? Needed?

**Comment by 6r1d** [comment]
Yes, pretty much, imagine making a copy of centrifuge array config!

**Comment by S-S-X** [comment]
Will add this taking #7 into account too, best to make this parametrised for API right away.
Good opportunity for moving current wand implementation behind API and configure it through registration method.

**Comment by S-S-X** [comment]
To do basics:
* change item recipe so that it returns stackable metatool:toolname .. "_empty"
* change reset recipe so that it also returns metatool:toolname .. "_empty"
* after node validation at metatool:on_use
  remove 1 metatool:toolname .. "_empty" from inventory
  create new ItemStack metatool:toolname itemstack and apply data to it
  return created metatool:toolname at end of metatool:on_use

Code to define new empty stackable items and reset recipe changes should go around here:
https://github.com/S-S-X/metatool/blob/master/metatool/api.lua#L36-L59

Code to generate tool with data and take empty tool from inventory should go around here: https://github.com/S-S-X/metatool/blob/master/metatool/api.lua#L96-L114

**Comment by S-S-X** [comment]
Found better approach as my belief about no-stacking-meta was wrong, instead items containing can be stacked very well.

So no new items but allow stacking and implement stack separation and recombining when metadata is applied.
