### ISSUE TITLE
digtron builder copy tool

### ISSUE THREAD

**Issue by BuckarooBanzay** [S-S-X/metatool#65]
Copies the builder-head settings from the digtron builder head

Not sure if that works out of the box because of the pseudo-inventory in the builder-node.
Its just an idea, haven't tried anything in the direction...

References:
* https://github.com/minetest-mods/digtron/blob/843dbd227658a93ee4df791bfdd3d136ee7adf85/nodes/node_builders.lua#L78-L81

**Comment by S-S-X** [comment]
Sounds like good and useful idea, probably should also add:
* Digger configuration
* Ejector configuration
* Controller configuration

> Not sure if that works out of the box because of the pseudo-inventory in the builder-node.

Should work nicely and probably a lot easier than technic chests or those "text nodes" :smile: 
Digtron also seems to always update formspec before sending it to player so no need to add dirty workarounds for that.
And on top of that there seems to be public API that should help a bit too, probably mostly `digtron.update_builder_item(pos)` needed for builders.

Diggers does not seem to need anything else than setting configuration values: https://github.com/minetest-mods/digtron/blob/master/nodes/node_diggers.lua#L84-L89

Ejector should get configuration through formspec callback, there's no API and it will not update formspec. But it is very simple configuration and should be just fine that way: https://github.com/minetest-mods/digtron/blob/master/nodes/node_item_ejector.lua#L152-L170

Controller might be a bit harder but not sure yet, also possible it works similar way to other components which could make configuration easier.

**Comment by S-S-X** [comment]
Cloned builder seems to work fine.
![tron-cloned-builder](https://user-images.githubusercontent.com/50966843/100948150-e2c0cd80-350f-11eb-92c5-6532dd572a1c.png)

~Diggers, ejector and~ controller to do.

**Comment by S-S-X** [comment]
Controller done. Everything seems to work as it should.
