### ISSUE TITLE
Rename tubetool and provide generic API for node metadata tools

### ISSUE THREAD

**Issue by S-S-X** [S-S-X/metatool#7]
Tubetool could be used for many things, current API alone allows easy creation of tools for cloning all kinds of node metadata.
Could be metatool, metacloner or something like that.

To make this more generic few things should be changed:
- [x] register_tool method to register new tool wands
  This should get wand name, recipe and textures.
- [x] change register_node to accept wand name.
- [x] nodes storage should have one more level for wand name.

Possible extras:
- [ ] data returned from defined copy functions could be better separated into internal and external parts.
- [ ] Allow defining required privileges to bypass protection checks for some nodes, this would allow defining administrative functions for tool.

**Comment by BuckarooBanzay** [comment]
> Tubetool could be used for many things, current API alone allows easy creation of tools for cloning all kinds of node metadata.

One thing that comes to mind is for copying luacontroller code: this would act as a copy-device and as backup too.

**Comment by S-S-X** [comment]
Added dev branch https://github.com/S-S-X/tubetool/tree/metatool for this.
First step would be to add wand registration method to API and add tool name for registered node storage without changing any of current behavior.

**Comment by S-S-X** [comment]
In the end there was only first step, I really couldn't see other steps through all that spaghetti and bolognese sauce...

**Comment by S-S-X** [comment]
Renamed to metatool, rename complete. Added alias tubetool:wand == metatool:tubetool
Moved more stuff to API from tubetool implementation.

Added event callbacks for tool definition, these are called depending on how tool is used:
* `on_read_node = function(tooldef, player, pointed_thing, node, pos)`
  This event callback should return data, group, description.
  Called when tool is used to read/copy data from pointed node.
* `on_write_node = function(tooldef, data, group, player, pointed_thing, node, pos)`
  Does not care about return value, in future this could maybe indicate success status by returning true/false.
  Called when tool is used to restore/write data to pointed node.

New callbacks replace `on_use` event method.

**Comment by S-S-X** [comment]
New ticket for remaining stuff.
