### ISSUE TITLE
Tubetool insecure fields for tp tube list form

### ISSUE THREAD

**Issue by S-S-X** [S-S-X/metatool#83]
```
<SwissalpS> SX: Bug: Invalid security token for form metatool:tubetool:teleport_tube_list
<SwissalpS> happens when selecting an entry from list, maybe this is in reboot-pipeline already
```

@SwissalpS This most probably means that token known by client is missing, this is probably because list selection change events does not send full form fields containing token but only selected elements.
So most probably `CHG` and `DCL` events: https://github.com/S-S-X/metatool/blob/fa38b3741d7ebf6bff816d4fe3a876c4e50b3972/tubetool/nodes/teleport_tube.lua#L38-L54

Security token is given for mt client so that client can prove that form was originally presented from server, if client sends form fields without token or with invalid token then form is not originally sent from server but instead client is making up formspec events.

Something I did not notice during testing of new formspec system, recheck and change form security `strict = false` + check form `security` arg when actually taking some action that is not just form field update.
https://github.com/S-S-X/metatool/blob/fa38b3741d7ebf6bff816d4fe3a876c4e50b3972/tubetool/nodes/teleport_tube.lua#L28

**Comment by S-S-X** [comment]
Could not reproduce problem by just bringing up teleport tube list and trying to change selection by clicking with mouse or changing selection with arrow keys. Tried with both direct tube sneak+use and stored channel sneak+use on other node that was not tube. That was with current master fa38b37.

It is possible that this is client specific thing and client I used for testing simply sends all fields while some other version wont send everything. Did first test with official stable mt client version 5.3, 5.2 and 5.0 (form looks terrible but works).

**Comment by S-S-X** [comment]
Also tested with 5.4 dev https://github.com/minetest/minetest/commit/af22dd86e3867a35e9e5ab911faa6e1e7671729d without being able to reproduce problem.
@SwissalpS what were exact steps you did to get that message? Also do you have any modifications (csm or mt client) that affect formspec handling/sending somehow?

**Comment by S-S-X** [comment]
Got idea how this could happen and also managed to reproduce issue. If you use tool fast enough to start multiple callbacks before formspec is displayed then it is possible that security token is wrong depending on which one of generated forms actually show up, if it is not latest then token is outdated and cannot be used.

If minetest can actually send formspecs in random order that cannot be easily predicted then I'd say this is bug in minetest engine.
However, message while using tool faster than ~light~ lag then message about invalid token might show up even while formspec does have correct token and works as expected.

**Comment by S-S-X** [comment]
In theory (if minetest will not retry like tcp proto would) at least this might also happen when network connection to server is not stable. If packets gets dropped situation can be like this:

1. Sneak+use tool, packet reaches server and executes callbacks. Formspec is created and sent to client.
2. Before client gets formspec from server sneak+use is done again, callbacks executed again.
3. Client receives first created formspec.
4. Second formspec never reaches client because packets get dropped, unstable network connection.
5. Now server has new security token, tried to sent it to client but client never received it. Client has open formspec with old token, messages sent using this expired formspec will not be accepted by server and instead chat message is sent about invalid token.

Behavior in this situation is correct, server and client are out of sync and fields are not to be trusted.

**Comment by SwissalpS** [comment]
I sneak+clicked one of my tp-tubes to bring up list and then clicked on an item in list, that printed the message.
Using 5.4.0 dev ecd4f client

**Comment by S-S-X** [comment]
> Using 5.4.0 dev ecd4f client

No patches applied to client you used for testing?
Especially src/gui/guiFormSpecMenu.cpp is clean directly from official mt engine repo?
And linux build with default cmake configuration and no configuration other than DRUN_IN_PLACE modified?

It might also be possible that something injects extra bytes to token field but not sure what could actually do this, token field is normal text field just hidden but might be editable somehow.

edit. Tested enough different versions to say this most probably is not engine issue when using official prebuilt release, also debugger pretty much confirmed that fields are sent always so it probably also is not missing formspec field.
That leaves possiblity that something changes formspec values, possible tool double use with unstable network connection or some weird bug destroying player specific server side `formdata` table.

**Comment by SwissalpS** [comment]
For prosperity, I follow-up information I passed through other channels:

OS: Fedora 33 Workstation
steps taken to build as described in official minetest how-to.
used flags: 
-DRUN_IN_PLACE=TRUE -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_CLIENT=TRUE -DBUILD_SERVER=TRUE
some builds I use -DCMAKE_BUILD_TYPE=Release

no CSM and no patches on C++ or Lua Code
not even texture packs on the tested builds; (just default client, default game and then pandorabox mod set - I digress).

**Comment by S-S-X** [comment]
I'll try to create debug branch for this and add some relevant debug output, this issue is bit weird as nobody else I asked can use formspecs with token without problems and so far I've not been able to reproduce issue. @SwissalpS would be very helpful if you could test after I've added debug version.

Interesting things for debugging would be:
* Token generated when form is rendered, that is `form:render()` called. https://github.com/S-S-X/metatool/blob/fa38b3741d7ebf6bff816d4fe3a876c4e50b3972/metatool/formspec.lua#L252-L253 https://github.com/S-S-X/metatool/blob/fa38b3741d7ebf6bff816d4fe3a876c4e50b3972/metatool/formspec.lua#L141-L144 https://github.com/S-S-X/metatool/blob/fa38b3741d7ebf6bff816d4fe3a876c4e50b3972/metatool/formspec.lua#L270-L271
* Token received from client with other form fields.
* Token stored in player data table, when it compared against token received from client. https://github.com/S-S-X/metatool/blob/fa38b3741d7ebf6bff816d4fe3a876c4e50b3972/metatool/formspec.lua#L198-L207
* Token stored in player data table, when it is added to storage.
* Creation of player / form specific data. https://github.com/S-S-X/metatool/blob/fa38b3741d7ebf6bff816d4fe3a876c4e50b3972/metatool/formspec.lua#L264-L268
* Removal of player / form specific data. https://github.com/S-S-X/metatool/blob/fa38b3741d7ebf6bff816d4fe3a876c4e50b3972/metatool/formspec.lua#L211-L212

So far I've not been able to find what could cause it, stepped through formspec send with gdb verifying data that engine collects using different client + server version combinations and everything I've done so far seems to just confirm that everything works correctly.

**Comment by S-S-X** [comment]
Cause found thanks to FeXoR after he sent packet capture recorded while using tool.
There token was correctly on formspec sent by server `2.14207394029348208164265088271350` but client sent `2.14207394029348208164265088271350eeeeeeeeee` back to server.

So it is after all very simple problem, sneak key that is set to `e` held while using tool. Field is active when formspec opens and gets repeating e appended.

**Comment by SwissalpS** [comment]
thanks @S-S-X and @FeXoR
fun to see why it didn't work
